[alias]
b = "build"
r = "run"
t = "test"
c = "check"
lint = "clippy --all-targets --all-features -- -D warnings"

[env]
WORKSPACE_PATH = { value = ".", relative = true }

[profile.dev]
incremental = true  # Keep for local dev
split-debuginfo = "unpacked"  # Can reduce size on macOS

[profile.release]
incremental = false  # Disable for release builds
